# Generated by Django 3.2.3 on 2021-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.CharField(max_length=4, verbose_name='Percent'),
        ),
    ]
