# Generated by Django 3.2.3 on 2021-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skill_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('projects', models.CharField(max_length=50, verbose_name='projects name')),
                ('projects_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
