# Generated by Django 3.2.3 on 2021-07-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
